models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null
      - name: country
        tests:
          - accepted_values:
              arguments:
                values: ['IT', 'FR', 'NL', 'DE']

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null
      - name: customer_id
        tests:
          - relationships:
              config:
                severity: warn
              arguments:
                to: ref('stg_customers')
                field: customer_id
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ['completed', 'shipped', 'returned', 'cancelled', 'pending']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              config:
                severity: warn
              arguments:
                to: ref('stg_orders')
                field: order_idmodels:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null
      - name: country
        tests:
          - accepted_values:
              arguments:
                values: ['IT', 'FR', 'NL', 'DE']

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null
      - name: customer_id
        tests:
          - relationships:
              config:
                severity: warn
              arguments:
                to: ref('stg_customers')
                field: customer_id
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ['completed', 'shipped', 'returned', 'cancelled', 'pending']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              config:
                severity: warn
              arguments:
                to: ref('stg_orders')
                field: order_id